# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'advanced-calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(290, 20, 281, 51))
        self.lineEdit.setStyleSheet("font: 30pt \"Franklin Gothic Demi Cond\";")
        self.lineEdit.setObjectName("lineEdit")
        self.ACbtn = QtWidgets.QPushButton(self.centralwidget)
        self.ACbtn.setGeometry(QtCore.QRect(290, 70, 75, 61))
        self.ACbtn.setStyleSheet("\n"
"background-color: rgb(70, 70, 70);\n"
"color: rgb(255, 255, 255);\n"
"font: 20pt \"Franklin Gothic Heavy\";")
        self.ACbtn.setObjectName("ACbtn")
        self.togglesignbtn = QtWidgets.QPushButton(self.centralwidget)
        self.togglesignbtn.setGeometry(QtCore.QRect(360, 70, 75, 61))
        self.togglesignbtn.setStyleSheet("background-color: rgb(70, 70, 70);\n"
"color: rgb(255, 255, 255);\n"
"font: 20pt \"Franklin Gothic Heavy\";")
        self.togglesignbtn.setObjectName("togglesignbtn")
        self.percentbtn = QtWidgets.QPushButton(self.centralwidget)
        self.percentbtn.setGeometry(QtCore.QRect(430, 70, 75, 61))
        self.percentbtn.setStyleSheet("background-color: rgb(70, 70, 70);\n"
"color: rgb(255, 255, 255);\n"
"font: 20pt \"Franklin Gothic Heavy\";")
        self.percentbtn.setObjectName("percentbtn")
        self.dividebtn = QtWidgets.QPushButton(self.centralwidget)
        self.dividebtn.setGeometry(QtCore.QRect(500, 70, 75, 61))
        self.dividebtn.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"font: 20pt \"Franklin Gothic Heavy\";")
        self.dividebtn.setObjectName("dividebtn")
        self.sevenbtn = QtWidgets.QPushButton(self.centralwidget)
        self.sevenbtn.setGeometry(QtCore.QRect(290, 130, 75, 61))
        self.sevenbtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(138, 138, 138);\n"
"font: 20pt \"Franklin Gothic Heavy\";")
        self.sevenbtn.setObjectName("sevenbtn")
        self.eightbtn = QtWidgets.QPushButton(self.centralwidget)
        self.eightbtn.setGeometry(QtCore.QRect(360, 130, 75, 61))
        self.eightbtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(138, 138, 138);\n"
"font: 20pt \"Franklin Gothic Heavy\";")
        self.eightbtn.setObjectName("eightbtn")
        self.ninebtn = QtWidgets.QPushButton(self.centralwidget)
        self.ninebtn.setGeometry(QtCore.QRect(430, 130, 75, 61))
        self.ninebtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(138, 138, 138);\n"
"font: 20pt \"Franklin Gothic Heavy\";")
        self.ninebtn.setObjectName("ninebtn")
        self.fourbtn = QtWidgets.QPushButton(self.centralwidget)
        self.fourbtn.setGeometry(QtCore.QRect(290, 190, 75, 61))
        self.fourbtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(138, 138, 138);\n"
"font: 20pt \"Franklin Gothic Heavy\";")
        self.fourbtn.setObjectName("fourbtn")
        self.multiplybtn = QtWidgets.QPushButton(self.centralwidget)
        self.multiplybtn.setGeometry(QtCore.QRect(500, 130, 75, 61))
        self.multiplybtn.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"font: 20pt \"Franklin Gothic Heavy\";")
        self.multiplybtn.setObjectName("multiplybtn")
        self.fivebtn = QtWidgets.QPushButton(self.centralwidget)
        self.fivebtn.setGeometry(QtCore.QRect(360, 190, 75, 61))
        self.fivebtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(138, 138, 138);\n"
"font: 20pt \"Franklin Gothic Heavy\";")
        self.fivebtn.setObjectName("fivebtn")
        self.sixbtn = QtWidgets.QPushButton(self.centralwidget)
        self.sixbtn.setGeometry(QtCore.QRect(430, 190, 75, 61))
        self.sixbtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(138, 138, 138);\n"
"font: 20pt \"Franklin Gothic Heavy\";")
        self.sixbtn.setObjectName("sixbtn")
        self.subtractbtn = QtWidgets.QPushButton(self.centralwidget)
        self.subtractbtn.setGeometry(QtCore.QRect(500, 190, 75, 61))
        self.subtractbtn.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"font: 20pt \"Franklin Gothic Heavy\";")
        self.subtractbtn.setObjectName("subtractbtn")
        self.zerobtn = QtWidgets.QPushButton(self.centralwidget)
        self.zerobtn.setGeometry(QtCore.QRect(290, 310, 141, 61))
        self.zerobtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(138, 138, 138);\n"
"font: 20pt \"Franklin Gothic Heavy\";")
        self.zerobtn.setObjectName("zerobtn")
        self.decimalpointbtn = QtWidgets.QPushButton(self.centralwidget)
        self.decimalpointbtn.setGeometry(QtCore.QRect(430, 310, 75, 61))
        self.decimalpointbtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(138, 138, 138);\n"
"font: 20pt \"Franklin Gothic Heavy\";")
        self.decimalpointbtn.setObjectName("decimalpointbtn")
        self.equalbtn = QtWidgets.QPushButton(self.centralwidget)
        self.equalbtn.setGeometry(QtCore.QRect(500, 310, 75, 61))
        self.equalbtn.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"font: 20pt \"Franklin Gothic Heavy\";")
        self.equalbtn.setObjectName("equalbtn")
        self.onebtn = QtWidgets.QPushButton(self.centralwidget)
        self.onebtn.setGeometry(QtCore.QRect(290, 250, 75, 61))
        self.onebtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(138, 138, 138);\n"
"font: 20pt \"Franklin Gothic Heavy\";")
        self.onebtn.setObjectName("onebtn")
        self.twobtn = QtWidgets.QPushButton(self.centralwidget)
        self.twobtn.setGeometry(QtCore.QRect(360, 250, 75, 61))
        self.twobtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(138, 138, 138);\n"
"font: 20pt \"Franklin Gothic Heavy\";")
        self.twobtn.setObjectName("twobtn")
        self.threebtn = QtWidgets.QPushButton(self.centralwidget)
        self.threebtn.setGeometry(QtCore.QRect(430, 250, 75, 61))
        self.threebtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(138, 138, 138);\n"
"font: 20pt \"Franklin Gothic Heavy\";")
        self.threebtn.setObjectName("threebtn")
        self.addbtn = QtWidgets.QPushButton(self.centralwidget)
        self.addbtn.setGeometry(QtCore.QRect(500, 250, 75, 61))
        self.addbtn.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"font: 20pt \"Franklin Gothic Heavy\";")
        self.addbtn.setObjectName("addbtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "calculator"))
        self.ACbtn.setText(_translate("MainWindow", "AC"))
        self.togglesignbtn.setText(_translate("MainWindow", "+/-"))
        self.percentbtn.setText(_translate("MainWindow", "%"))
        self.dividebtn.setText(_translate("MainWindow", "/"))
        self.sevenbtn.setText(_translate("MainWindow", "7"))
        self.eightbtn.setText(_translate("MainWindow", "8"))
        self.ninebtn.setText(_translate("MainWindow", "9"))
        self.fourbtn.setText(_translate("MainWindow", "4"))
        self.multiplybtn.setText(_translate("MainWindow", "*"))
        self.fivebtn.setText(_translate("MainWindow", "5"))
        self.sixbtn.setText(_translate("MainWindow", "6"))
        self.subtractbtn.setText(_translate("MainWindow", "-"))
        self.zerobtn.setText(_translate("MainWindow", "0"))
        self.decimalpointbtn.setText(_translate("MainWindow", "."))
        self.equalbtn.setText(_translate("MainWindow", "="))
        self.onebtn.setText(_translate("MainWindow", "1"))
        self.twobtn.setText(_translate("MainWindow", "2"))
        self.threebtn.setText(_translate("MainWindow", "3"))
        self.addbtn.setText(_translate("MainWindow", "+"))
        self.lineEdit.setReadOnly(True)
        self.btns=[self.zerobtn,self.decimalpointbtn,self.percentbtn,self.multiplybtn,self.addbtn,self.onebtn,
        self.threebtn,self.twobtn,self.fivebtn,self.fourbtn,self.ninebtn,self.eightbtn,self.sevenbtn,self.sixbtn,
        self.dividebtn,self.subtractbtn]

        self.operators=[self.addbtn,self.subtractbtn,self.multiplybtn,self.dividebtn,self.percentbtn]
        for btn in self.btns:
            btn.clicked.connect(self.appendvalues)
        self.ACbtn.clicked.connect(self.resettext)
        self.togglesignbtn.clicked.connect(self.togglesign)
        self.equalbtn.clicked.connect(self.calculate)
        self.isdecimalused=False
        self.isresultvisible=True

    def resettext(self):
        self.lineEdit.setText("")            

    def togglesign(self):
        text=self.lineEdit.text()
        if text.startswith("-"):
            text=text[1:]
        else:
            text="-"+text
        self.lineEdit.setText(text)

    def appendvalues(self):    
        btn=self.sender()
        text=self.lineEdit.text()

        if btn in self.operators:
            self.isdecimalused=False    
            if ord(text[-1])>=48 and ord(text[-1])<=57:    
                text+=btn.text()
            else:
                text=text[:1]+btn.text() 
        elif self.isresultvisible:
            self.lineEdit.setText("")
            self.isresultvisible=False

        elif btn==self.decimalpointbtn:
            if not self.isdecimalused:    
                text+=btn.text()
                self.isdecimalused    
        else:
            text+=btn.text()

        self.lineEdit.setText(text)  
   
    def calculate(self):
        text = self.lineEdit.text()
        if len(text)>0:
            if ord(text[-1]) >= 48 and ord(text[-1]) <= 57:
                result = str(eval(text))
                if result !=text:
                    self.lineEdit.setText(str(result))
                    self.isresultvisible=True

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
