# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.basic = QtWidgets.QLabel(self.centralwidget)
        self.basic.setGeometry(QtCore.QRect(310, 20, 161, 21))
        self.basic.setStyleSheet("color: rgb(255, 56, 21);\n"
"font: 75 14pt \"Segoe Print\";")
        self.basic.setObjectName("basic")
        self.secondnumber = QtWidgets.QLabel(self.centralwidget)
        self.secondnumber.setGeometry(QtCore.QRect(50, 70, 161, 21))
        self.secondnumber.setStyleSheet("color: rgb(255, 56, 21);\n"
"font:14pt \"Segoe Script\";")
        self.secondnumber.setObjectName("secondnumber")
        self.firstnumber = QtWidgets.QLabel(self.centralwidget)
        self.firstnumber.setGeometry(QtCore.QRect(60, 160, 161, 21))
        self.firstnumber.setStyleSheet("color: rgb(255, 56, 21);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"MS PMincho\";\n"
"color: rgb(170, 85, 255);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"font: 8pt \"Segoe Script\";\n"
"font: 10pt \"Segoe Script\";\n"
"font: 75 14pt \"Segoe Print\";")
        self.firstnumber.setObjectName("firstnumber")
        self.Result = QtWidgets.QLabel(self.centralwidget)
        self.Result.setGeometry(QtCore.QRect(70, 270, 161, 21))
        self.Result.setStyleSheet("color: rgb(255, 56, 21);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"MS PMincho\";\n"
"color: rgb(170, 85, 255);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"font: 8pt \"Segoe Script\";\n"
"font: 10pt \"Segoe Script\";\n"
"font: 75 14pt \"Segoe Print\";")
        self.Result.setObjectName("Result")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(320, 70, 151, 31))
        self.lineEdit.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(320, 160, 151, 31))
        self.lineEdit_2.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(320, 270, 151, 31))
        self.lineEdit_3.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(60, 380, 91, 81))
        self.pushButton.setStyleSheet("background-color: rgb(255, 6, 31);\n"
"font: 26pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 380, 91, 81))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 6, 31);\n"
"font: 26pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(320, 380, 91, 81))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 6, 31);\n"
"font: 26pt \"MS Shell Dlg 2\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(450, 380, 91, 81))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 6, 31);\n"
"font: 26pt \"MS Shell Dlg 2\";")
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.basic.setText(_translate("MainWindow", "Basic Calculator"))
        self.secondnumber.setText(_translate("MainWindow", "First Number"))
        self.firstnumber.setText(_translate("MainWindow", "enter second no."))
        self.Result.setText(_translate("MainWindow", "Result"))
        self.pushButton.setText(_translate("MainWindow", "+"))
        self.pushButton_2.setText(_translate("MainWindow", "-"))
        self.pushButton_3.setText(_translate("MainWindow", "*"))
        self.pushButton_4.setText(_translate("MainWindow", "/"))
        
        self.pushButton.clicked.connect(self.add)
        self.pushButton_2.clicked.connect(self.sub)
        self.pushButton_3.clicked.connect(self.mul)
        self.pushButton_4.clicked.connect(self.div)
 
    def getnumbers(self):
        f_num=int(self.secondnumber.text())
        s_num=int(self.firstnumber.text())
        return f_num,s_num

    def add(self):
        x,y=self.getnumbers()
        Result=str(x+y)
        self.Result.setText(Result)   
        #print("add called...")
    def sub(self):
        x,y=self.getnumbers() 
        Result=str(x-y)
        self.Result.setText(Result)    
        #print("sub called...")
    def mul(self):
        x,y=self.getnumbers() 
        Result=str(x*y)
        self.Result.setText(Result)    
        #print("mul called...")
    def div(self):
        x,y=self.getnumbers() 
        Result=str(x/y)
        self.Result.setText(Result)
        #print("div called...")            

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
