# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'musicplayer.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import pygame
import random
import threading
import mutagen
pygame.mixer.init()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.commonPath="C:/Python38/advance/desktopapp/icons/"  
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(736, 507)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.musicontrollerframe = QtWidgets.QFrame(self.centralwidget)
        self.musicontrollerframe.setGeometry(QtCore.QRect(0, 360, 731, 101))
        self.musicontrollerframe.setStyleSheet("background-color: rgb(205, 251, 255);\n"
"background-color: rgb(217, 239, 255);")
        self.musicontrollerframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.musicontrollerframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.musicontrollerframe.setObjectName("musicontrollerframe")
        self.horizontalSlider = QtWidgets.QSlider(self.musicontrollerframe)
        self.horizontalSlider.setGeometry(QtCore.QRect(20, 10, 691, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.shufflebtn = QtWidgets.QPushButton(self.musicontrollerframe)
        self.shufflebtn.setGeometry(QtCore.QRect(80, 30, 68, 60))
        self.shufflebtn.setStyleSheet(f"background-image:url({self.commonPath +'shuffle_btn.png'});background-color: rgb(10, 169, 255);")
        self.shufflebtn.setText("")
        self.shufflebtn.setObjectName("shufflebtn")
        self.previousbtn = QtWidgets.QPushButton(self.musicontrollerframe)
        self.previousbtn.setGeometry(QtCore.QRect(190, 30, 70, 60))
        self.previousbtn.setStyleSheet(f"background-image:url({self.commonPath +'prev_btn.png'});background-color: rgb(10, 169, 255);")
        self.previousbtn.setText("")
        self.previousbtn.setObjectName("previousbtn")
        self.playpausebtn = QtWidgets.QPushButton(self.musicontrollerframe)
        self.playpausebtn.setGeometry(QtCore.QRect(300, 30, 70, 60))
        self.playpausebtn.setStyleSheet(f"background-image:url({self.commonPath +'play_btn.png'});background-color: rgb(10, 169, 255);")
        self.playpausebtn.setText("")
        self.playpausebtn.setObjectName("playpausebtn")
        self.nextbtn = QtWidgets.QPushButton(self.musicontrollerframe)
        self.nextbtn.setGeometry(QtCore.QRect(410, 30, 70, 60))
        self.nextbtn.setStyleSheet(f"background-image:url({self.commonPath +'next.png'});background-color: rgb(10, 169, 255);")
        self.nextbtn.setText("")
        self.nextbtn.setObjectName("nextbtn")
        self.repeatbtn = QtWidgets.QPushButton(self.musicontrollerframe)
        self.repeatbtn.setGeometry(QtCore.QRect(520, 30, 70, 60))
        self.repeatbtn.setStyleSheet("background-color: rgb(10, 169, 255);")
        self.repeatbtn.setText("")
        self.repeatbtn.setObjectName("repeatbtn")
        self.songcurrentduration = QtWidgets.QLabel(self.musicontrollerframe)
        self.songcurrentduration.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.songcurrentduration.setObjectName("songcurrentduration")
        self.songtotalduration = QtWidgets.QLabel(self.musicontrollerframe)
        self.songtotalduration.setGeometry(QtCore.QRect(680, 40, 31, 16))
        self.songtotalduration.setObjectName("songtotalduration")
        self.playlistframe = QtWidgets.QFrame(self.centralwidget)
        self.playlistframe.setGeometry(QtCore.QRect(480, 0, 241, 361))
        self.playlistframe.setStyleSheet("background-color: rgb(217, 242, 255);")
        self.playlistframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.playlistframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.playlistframe.setObjectName("playlistframe")
        self.playlisttable = QtWidgets.QTableWidget(self.playlistframe)
        self.playlisttable.setGeometry(QtCore.QRect(20, 40, 211, 321))
        self.playlisttable.setStyleSheet("font: 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(96, 208, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.playlisttable.setObjectName("playlisttable")
        self.playlisttable.setColumnCount(2)
        self.playlisttable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.playlisttable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.playlisttable.setHorizontalHeaderItem(1, item)
        self.playlistheading = QtWidgets.QLabel(self.playlistframe)
        self.playlistheading.setGeometry(QtCore.QRect(100, 10, 71, 21))
        self.playlistheading.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.playlistheading.setObjectName("playlistheading")
        self.currentlyplayingframe = QtWidgets.QFrame(self.centralwidget)
        self.currentlyplayingframe.setGeometry(QtCore.QRect(-1, -1, 201, 361))
        self.currentlyplayingframe.setStyleSheet("background-color: rgb(217, 242, 255);")
        self.currentlyplayingframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.currentlyplayingframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.currentlyplayingframe.setObjectName("currentlyplayingframe")
        self.currentlyplayingheading = QtWidgets.QLabel(self.currentlyplayingframe)
        self.currentlyplayingheading.setGeometry(QtCore.QRect(30, 0, 161, 31))
        self.currentlyplayingheading.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.currentlyplayingheading.setObjectName("currentlyplayingheading")
        self.currentlyplayingsong = QtWidgets.QLabel(self.currentlyplayingframe)
        self.currentlyplayingsong.setGeometry(QtCore.QRect(30, 40, 161, 31))
        self.currentlyplayingsong.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.currentlyplayingsong.setObjectName("currentlyplayingsong")
        self.songlistframe = QtWidgets.QFrame(self.centralwidget)
        self.songlistframe.setGeometry(QtCore.QRect(199, 0, 281, 361))
        self.songlistframe.setStyleSheet("background-color: rgb(217, 242, 255);")
        self.songlistframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.songlistframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.songlistframe.setObjectName("songlistframe")
        self.songactiontable = QtWidgets.QListWidget(self.songlistframe)
        self.songactiontable.setGeometry(QtCore.QRect(10, 40, 171, 311))
        self.songactiontable.setStyleSheet("background-color: rgb(96, 208, 255);")
        self.songactiontable.setObjectName("songactiontable")
        self.songstable = QtWidgets.QListWidget(self.songlistframe)
        self.songstable.setGeometry(QtCore.QRect(200, 41, 81, 311))
        self.songstable.setStyleSheet("background-color: rgb(96, 208, 255);")
        self.songstable.setObjectName("songstable")
        self.featuredsongsheading = QtWidgets.QLabel(self.songlistframe)
        self.featuredsongsheading.setGeometry(QtCore.QRect(90, 10, 141, 20))
        self.featuredsongsheading.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.featuredsongsheading.setObjectName("featuredsongsheading")
        #self.splashscreenframe = QtWidgets.QFrame(self.centralwidget)
        #self.splashscreenframe.setGeometry(QtCore.QRect(0, 0, 731, 471))
        #self.splashscreenframe.setStyleSheet("background-color: rgb(255, 255, 255);")
        #self.splashscreenframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        #33self.splashscreenframe.setFrameShadow(QtWidgets.QFrame.Raised)
        #self.splashscreenframe.setObjectName("splashscreenframe")
        #self.welcomelable = QtWidgets.QLabel(self.splashscreenframe)
        #self.welcomelable.setGeometry(QtCore.QRect(200, 40, 311, 31))
        #self.welcomelable.setStyleSheet("font: 75 20pt \"Mongolian Baiti\";")
        #self.welcomelable.setObjectName("welcomelable")
        #3self.listnowbtn = QtWidgets.QPushButton(self.splashscreenframe)
        #self.listnowbtn.setGeometry(QtCore.QRect(300, 140, 75, 23))
        #self.listnowbtn.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n""background-color: rgb(245, 230, 255);")
        #self.listnowbtn.setObjectName("listnowbtn")
        #self.imagelabel = QtWidgets.QLabel(self.splashscreenframe)
        #self.imagelabel.setGeometry(QtCore.QRect(-1, -1, 800, 600))
        #self.imagelabel.setText("")
        #self.imagelabel.setObjectName("imagelabel")

        #self.wallpaper = QtGui.QPixmap("C:\\Python38\\advance\\desktopapp\\music.jpg")
        #self.imagelabel.setPixmap(self.wallpaper)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 736, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.songcurrentduration.setText(_translate("MainWindow", "00:00"))
        self.songtotalduration.setText(_translate("MainWindow", "00:00"))
        item = self.playlisttable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "song Name"))
        item = self.playlisttable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Action"))
        self.playlistheading.setText(_translate("MainWindow", "PLAYLIST"))
        self.currentlyplayingheading.setText(_translate("MainWindow", "CURRENTLY PLAYING"))
        self.currentlyplayingsong.setText(_translate("MainWindow", "-"))
        self.featuredsongsheading.setText(_translate("MainWindow", "FEATURED SONGS"))
        #self.welcomelable.setText(_translate("MainWindow", "Welcome to XOMP player"))
        #self.listnowbtn.setText(_translate("MainWindow", "List Now"))
        self.issuffle=False
        self.shufflebtn.clicked.connect(self.toggleshuffle)
        self.previousbtn.clicked.connect(self.previoussong)
        self.nextbtn.clicked.connect(self.nextsong)
        self.songspath="C:/Python38/advance/desktopapp/songs/"
        self.featuredsongs=os.listdir("C:/Python38/advance/desktopapp/songs/")
        self.playlistsongs=[]
        self.songs=self.featuredsongs
        self.selectedplaylist="featuredsongs"

        for i in range(len(self.featuredsongs)):
            listItem = QtWidgets.QListWidgetItem()
            listItem.setText(self.featuredsongs[i])
            self.songactiontable.addItem(listItem)
            listItem = QtWidgets.QListWidgetItem()
            listItem.setIcon(QtGui.QIcon(f"{self.commonPath}add_btn.png"))
            self.songstable.addItem(listItem)

        tableItem = QtWidgets.QTableWidgetItem()
        tableItem.setText("Daaru Party-(Mr-jatt.com).mp3")
        tableItem2 = QtWidgets.QTableWidgetItem()
        tableItem2.setIcon(QtGui.QIcon(f"{self.commonPath}delete_btn.png"))
        self.playlisttable.insertRow(0)
        self.playlisttable.setItem(0, 0, tableItem)
        self.playlisttable.setItem(0, 1, tableItem2)

        self.songactiontable.itemClicked.connect(self.selectfeaturedsong)
        self.playlisttable.itemClicked.connect(self.selectUserPlaylistSong)
        self.playpausebtn.clicked.connect(self.playsong)
        self.horizontalSlider.setDisabled(True)
        self.horizontalSlider.setMinimum(0)
        self.t = threading.Thread(target = self.changeSliderPosition)
        self.t.start()

    def changeSliderPosition(self):
        while True:
            print("slider position changed...")    
    
    def playsong(self):
        pygame.mixer.music.load(self.songspath+ self.currentsong)
        pygame.mixer.music.play()
        self.showCurrentSong = self.currentsong.replace(
            " ", "\n").replace("_", "\n")
        self.currentlyplayingsong.setText("Daaru Party")
        self.horizontalSlider.setDisabled(False)
        songFile = mutagen.File(self.songspath + self.currentsong)
        songLength = songFile.info.length
        self.horizontalSlider.setMaximum(songLength)

    def previoussong(self):
        if self.selectedplaylist == "user playlist":
            self.songs = self.playlistsongs
        else:
            self.songs = self.featuredsongs

        if self.issuffle:
            self.songIndex = random.randint(0, len(self.songs) - 1)
        else:
            self.songIndex = self.songs.index(self.currentsong)
            self.songIndex -= 1
            if (self.songIndex == len(self.songs)):
                self.songIndex = 0
        self.currentSong = self.songs[self.songIndex]
        print(self.currentsong)
        self.playsong()

    def nextsong(self):
        if self.selectedplaylist == "user playlist":
            self.songs = self.playlistsongs
        else:
            self.songs = self.featuredsongs

        if self.issuffle:
            self.songIndex = random.randint(0, len(self.songs) - 1)
        else:
            self.songIndex = self.songs.index(self.currentsong)
            self.songIndex += 1
            if (self.songIndex == len(self.songs)):
                self.songIndex = 0
        self.currentsong = self.songs[self.songIndex]
        print(self.currentsong)
        self.playsong()

    def toggleshuffle(self):
        self.issuffle = not self.issuffle
        print("shuffle - ", self.issuffle)
        if self.issuffle:
            self.shufflebtn.setStyleSheet(
                f"background-image: url({self.commonPath}shuffle_btn.png); background-color: #eea639;")
        else:
            self.shufflebtn.setStyleSheet(
                f"background-image: url({self.commonPath + 'shuffle_btn.png'}); background-color: rgb(57, 163, 238);")

    def selectfeaturedsong(self,item):
        self.selectedplaylist="featured songs"
        self.currentsong=item.text()
        print(self.currentsong)    
 
    def selectUserPlaylistSong(self, item):
        self.selectedPlaylist = "user playlist"
        self.currentsong = item.text()
        print(self.currentsong)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
